development:
  sessions:
    default:
      database: router
      hosts:
        - localhost:27017
      options:
        safe:
          w: 1
        consistency: :strong
test:
  sessions:
    default:
      database: router_api_test
      hosts:
        - localhost:27017
      options:
        safe:
          w: 1
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
