development:
  sessions:
    default:
      database: router
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
        read: primary

        # Change the default consistency model to primary, secondary.
        # 'secondary' will send reads to secondaries, 'primary' sends everything
        # to master. (default: primary)
        # read: secondary_preferred

test:
  sessions:
    default:
      database: router_api_test
      hosts:
        - localhost:27017
      options:
        write:
          w: 1
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
